[package]
name = "cli-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
home = "0.5"
crossterm = "0.27"
regex = "1.10"
